In [1]:
x = 10 # int
y = 10.23 #float

In [2]:
type(x)

int

In [3]:
type(y)

float

In [4]:
s = 'Welcome to Python'
type(s)

str

In [5]:
y1 = int(y) 
type(y1)

int

In [6]:
x1 = float(x)
type(x1)

float

In [7]:
x1

10.0

In [11]:
a1 = '123'
print (int(a1))

123


In [12]:
type(a1)

str

In [13]:
l = [2,4,6,8,10]
type(l)

list

In [14]:
l[0]

2

In [15]:
l[4]

10

In [17]:
l[:3]

[2, 4, 6]

In [18]:
# start:end-1  - range selection
l[0:3]

[2, 4, 6]

In [19]:
l[1:4]

[4, 6, 8]

In [21]:
l[-2]

8

In [22]:
l[-3:]

[6, 8, 10]

In [28]:
# start:end-1:step
l[:5:2]

[2, 6, 10]

In [29]:
# start:end-1:step
l[:3:2]

[2, 6]

In [30]:
l

[2, 4, 6, 8, 10]

In [31]:
l[2]=666
l

[2, 4, 666, 8, 10]

In [32]:
# list is mutable (modifiable)
del l[2]
l

[2, 4, 8, 10]

In [33]:
# crud (insert, read, update and delete)
l.append(12)

In [34]:
l

[2, 4, 8, 10, 12]

<built-in method reverse of list object at 0x7f1594e753c8>


In [37]:
l

[2, 4, 8, 10, 12]

In [39]:
sorted(l, reverse=True)

[12, 10, 8, 4, 2]

In [40]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [41]:
l2 = l

In [42]:
type(l2)

list

In [44]:
l2

[2, 4, 8, 10, 12]

In [48]:
# list comprehension
l3 = []
for i in l2:
     l3.append(i+10)
print(l3)    

12
14
18
20
22
[12, 14, 18, 20, 22]


In [49]:
[i + 10 for i in l2]

[12, 14, 18, 20, 22]

In [50]:
# tuples () to define tuple. its immutable

t = (2,3,4,5,6)
type(t)

tuple

In [51]:
t[0]=222

TypeError: 'tuple' object does not support item assignment

In [52]:
del t[0]

TypeError: 'tuple' object doesn't support item deletion

In [53]:
t

(2, 3, 4, 5, 6)

In [54]:
t += (777,)
t

(2, 3, 4, 5, 6, 777)

In [55]:
d = {'apple':100,'Mango':200,'Pears':10}
type(d)

dict

In [56]:
d['PineApple']=123

In [57]:
d

{'apple': 100, 'Mango': 200, 'Pears': 10, 'PineApple': 123}

In [58]:
d['apple']=50

In [59]:
d

{'apple': 50, 'Mango': 200, 'Pears': 10, 'PineApple': 123}

In [60]:
d['Mango']='apple'

In [61]:
d

{'apple': 50, 'Mango': 'apple', 'Pears': 10, 'PineApple': 123}

In [62]:
d.keys()

dict_keys(['apple', 'Mango', 'Pears', 'PineApple'])

In [63]:
d.values()

dict_values([50, 'apple', 10, 123])

In [64]:
del d['Mango']

In [65]:
d

{'apple': 50, 'Pears': 10, 'PineApple': 123}

In [67]:
s1 = {23,'S',123,11.12,23}
type(s1)

set

In [68]:
s1

{11.12, 123, 23, 'S'}

In [69]:
l

[2, 4, 8, 10, 12]

In [70]:
l.append(2)

In [71]:
l

[2, 4, 8, 10, 12, 2]

In [82]:
l = list(set(l))

In [83]:
type(l)

list

In [84]:
# sapient 
# MCQ 
l4 = [l,l2]
l4

[[2, 4, 8, 10, 12], [2, 4, 8, 10, 12, 2]]

In [86]:
l4[0][3]

10

In [87]:
l4[1][4]

12

In [76]:
type(l4)

list

In [88]:
s1 = {}
type(s1)

dict

In [89]:
import numpy as np

In [90]:
arr1 = np.array([2,3,4])
type(arr1)

numpy.ndarray

In [93]:
arr2 = np.array([3,4,5])
type(arr2)

numpy.ndarray

In [94]:
arr1.shape

(3,)

In [95]:
arr1 + arr2

array([5, 7, 9])

In [96]:
l 

[2, 4, 8, 10, 12]

In [97]:
l2

[2, 4, 8, 10, 12, 2]

In [98]:
l + l2

[2, 4, 8, 10, 12, 2, 4, 8, 10, 12, 2]

In [103]:
arr1  + 2

array([4, 5, 6])

In [100]:
arr1

array([2, 3, 4])

In [102]:
l + 2

TypeError: can only concatenate list (not "int") to list

In [106]:
arr3 =np.concatenate([arr1,arr2]).reshape(3,2)

In [108]:
arr3.shape

(3, 2)

In [109]:
arr3

array([[2, 3],
       [4, 3],
       [4, 5]])

In [112]:
np.savetxt('arr3values.txt',arr3, delimiter=',')
np.loadtxt('arr3values.txt',delimiter=',')

array([[2., 3.],
       [4., 3.],
       [4., 5.]])

In [116]:
# while(expression):
#  statement1 
#  statement2

i = 1
while ( i < 5):
    print(i)
    i += 1  # i = i + 1
else:
    print('Max  value is ' ,i)

1
2
3
4
Max  value is  5


In [123]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [119]:
list(range(1,5))

[1, 2, 3, 4]

In [121]:
np.arange(1,5)

array([1, 2, 3, 4])

In [125]:
for i in range(1,11):
    if (i == 4 or i == 8):
        continue 
    print(i)

1
2
3
5
6
7
9
10


In [126]:
for i in range(1,11):
    if (i == 4 or i == 8):
        break 
    print(i)

1
2
3


In [133]:
def addValues(basic,hra,lop):
    res = ((basic+hra) - lop)
    return(res)

In [134]:
netsal = addValues(100000,1223,234)
netsal

100989

In [136]:
# lambda arguments:expression
l = lambda basic,hra,lop: ((basic+hra)-lop)
l(100000,1223,234)

100989

In [139]:
l = [2,3,4,5,6,7,8,9]


In [144]:
for i in l:
    if ( i % 2 == 0):
        print (i)

2
4
6
8


In [143]:
# filter function takes both function and list as argments

list(filter (lambda x:x % 2 == 0  , l))

[2, 4, 6, 8]

In [145]:
list(map(lambda x:x + 2, l))

[4, 5, 6, 7, 8, 9, 10, 11]

In [146]:
l

[2, 3, 4, 5, 6, 7, 8, 9]

In [149]:
from functools import reduce 
reduce(lambda x,y:x + y, l)

44

In [ ]:
(((2+3)+4)+5)

In [161]:
import pandas as pd  # wed mcinny

In [162]:
df  = pd.reaxd_csv("SalesJan2009.csv", delimiter=',')
df.head()

pd.read

AttributeError: module 'pandas' has no attribute 'read'